const components = {
            adu	:	"Airduct"	,
aoa	:	"Air opening assembly"	,
ard	:	"Anti rack device",
aro	:	"Anti rack omega",
arp	:	"Anti rack plate"	,
ars	:	"Anti rack spigot"	,
ats	:	"Replace Safety/Anti-Theft String/Wire	"	,
bdb	:	"Underfloor diagonal bracing"	,
ccf	:	"Top plate of Hinge Assy	"	,
cfg	:	"Corner fitting	"	,
cid	:	"Container identification device	"	,
cma	:	"Cross member assembly"	,
cmc	:	"Cross-member T-clip"	,
cmf	:	"Cross member fixing plate"	,
cml	:	"Cross member lower flange"	,
cmo	:	"Outrigger"	,
cms	:	"Cross member whole section"	,
cmu	:	"Cross member upper flange"	,
cmw	:	"Cross member web"	,
cos	:	"Clip-on genset clamp socket"	,
cpa	:	"Corner post"	,
cpg	:	"Corner post gusset"	,
cpi	:	"Corner post inner piece"	,
cpj	:	"Corner post J-bar"	,
cpl	:	"Corner post hinge lug"	,
cpo	:	"Corner post outer piece"	,
cpr	:	"Coner post reinforcement"	,
cps	:	"Corner post single piece"	,
cpt	:	"Corner post whole section"	,
csp	:	"Coil Spring Connection (Wedge)"	,
daa	:	"Door - complete without hardware"	,
dah	:	"Door - complete with hardware"	,
dca	:	"Door with hardware - corrugated"	,
dcs	:	"Door customs seal point"	,
def	:	"End frame - drop or collapsible"	,
dfa	:	"Door with hardware - flat"	,
dfs	:	"Door/front sill stiffener"	,
dgr	:	"Door gear complete"	,
dhb	:	"Hinge bush"	,
dhc	:	"Door handle catch"	,
dhl	:	"Door handle lock assembly"	,
dhr	:	"Door handle retainer"	,
dpl	:	"Door stop/slam (security) plate"	,
dpr	:	"Door plate rivets"	,
drh	:	"Door chain hook"	,
drl	:	"Door retainer lug"	,
drs	:	"Roller shutter door"	,
drt	:	"Door retainer"	,
dsb	:	"Door stiffener - bottom edge"	,
dsc	:	"Door stiffener - centreline edge"	,
dsh	:	"Door stiffener - hinge side edge"	,
dsm	:	"Door stiffener - vertical panel"	,
dso	:	"Door security plug - left hand door"	,
dst	:	"Door stiffener - top edge"	,
dsv	:	"Door stiffner - vertical edge"	,
eaa	:	"Endwall - complete assembly"	,
ebr	:	"Collapsible flatrack endwall bottom rail"	,
ecc	:	"Container identification device battery"	,
efh	:	"Hinge - end frame assembly"	,
eha	:	"Endwall heel assembly"	,
ehb	:	"Endwall heel plate"	,
ehp	:	"Endwall heel pin"	,
ehr	:	"Endwall heel pin retainer"	,
ela	:	"Endwall latch assembly"	,
elb	:	"Endwall latch bush"	,
elh	:	"End post down lock handle/header lock handle"	,
elp	:	"Endwall latch pin"	,
elr	:	"Endwall latch pin retainer"	,
els	:	"Endwall latch rubber buffer"	,
elu	:	"Endwall latch bracket"	,
etb	:	"Endwall torsion bar"	,
etc	:	"Endwall torsion bar bearing brackets"	,
fhs	:	"Hat section"	,
fla	:	"Forklift pocket assembly"	,
flb	:	"Laminated plank"	,
fll	:	"Forklift pocket lower flange"	,
flp	:	"Forklift pocket top plate"	,
fls	:	"Forklift pocket strap"	,
flt	:	"Forklift pocket whole transverse section"	,
flu	:	"Forklift pocket upper flange"	,
flw	:	"Forklift pocket web"	,
fpb	:	"Plain Plank"	,
fpp	:	"Plywood panel"	,
frs	:	"Counter Balance Coil Spring"	,
fsa	:	"Floor support angle"	,
fsp	:	"Floor - steel plate combination"	,
ftp	:	"Threshold plate"	,
fts	:	"Floorboard tapping screw"	,
fun	:	"Fumigating nozzle"	,
fwa	:	"Wood floor assembly"	,
fws	:	"Combination steel and wood floor"	,
gct	:	"Door gasket corner tape"	,
gin	:	"Gasket - inner"	,
gio	:	"Gasket - inner and outer"	,
grf	:	"Gasket retainer fastener"	,
grs	:	"Gasket retainer strip"	,
gta	:	"Gasket assembly"	,
gto	:	"Gasket - outer"	,
had	:	"Discharge hatch assembly"	,
hal	:	"Loading hatch assembly"	,
hcp	:	"Hatch customs point"	,
hcv	:	"Hatch cover"	,
hds	:	"Hatch discharge sleeve"	,
hep	:	"Header extension plate"	,
hga	:	"Hinge assembly"	,
hgb	:	"Hinge blade"	,
hgi	:	"Inner Hinge Assy (Wedge)"	,
hgo	:	"Outer Hinge Assy"	,
hgp	:	"Hinge pin"	,
hgt	:	"Hatch gasket"	,
hhc	:	"Hatch handle catch"	,
hhg	:	"Hatch hinge"	,
hhr	:	"Hatch handle retainer"	,
hla	:	"End post down lock/header lock"	,
hlb	:	"Hatch locking bar"	,
hlh	:	"Hatch locking handle"	,
hlm	:	"Hatch locking mechanism"	,
hlp	:	"End post down lock pin/header lock pin"	,
hlr	:	"Header lock guide plate or retainer"	,
hls	:	"End post down lock spring/header lock spring"	,
hpc	:	"Header pin chain"	,
hph	:	"Header pin handle"	,
hra	:	"Hanging rail assembly"	,
hrb	:	"Hanging rail bar"	,
hrh	:	"Hanging rail hook"	,
hwh	:	"Hardware - Huckbolts"	,
hwr	:	"Hardware"	,
ila	:	"Interlink ring"	,
ilb	:	"Interlink bar"	,
ilc	:	"Interlocking bolt assembly"	,
ild	:	"Interlocking bolt"	,
ilh	:	"Interlocking bolt handle"	,
ilk	:	"Interlocking bolt bracket"	,
ill	:	"Interlocking bolt latch"	,
ils	:	"Interlocking bolt backstop"	,
itp	:	"Intermediate post (Openside)"	,
itq	:	"Timber slats (Openside)"	,
kbz	:	"Grease or Zirc fitting"	,
ktw	:	"Twistlock"	,
lba	:	"Locking bar assembly"	,
lbb	:	"Locking bar bracket"	,
lbc	:	"Locking bar cam"	,
lbf	:	"Door customs flap"	,
lbg	:	"Locking bar guide"	,
lbh	:	"Locking bar handle"	,
lbl	:	"Locking bar lug"	,
lbn	:	"Locking bar nut"	,
lbr	:	"Locking bar rod"	,
lbt	:	"Lock bolt"	,
lfb	:	"Locking Flap Bracket"	,
lfp	:	"Locking Flap Pin"	,
lhf	:	"Locking Hammer Flap/Safety Catch Tongue"	,
lhh	:	"Locking bar handle hub"	,
lms	:	"Locking mechanism - sill to end frame"	,
lpa	:	"Complete locking pin shaft assy/Slide Hammer assy"	,
lpb	:	"Locking pin shaft bar only"	,
lph	:	"Taper Locking Pin/Sliding Hammer Head"	,
lpp	:	"Locking pin - end frame to side rail"	,
lps	:	"Locking pin - sill to corner fitting"	,
lsa	:	"Cargo securing device"	,
lsb	:	"Lashing bar"	,
lsf	:	"Leaf Spring Follower/Former"	,
lsr	:	"Lashing ring"	,
lss	:	"Locking pin shaft stopper ring"	,
mad	:	"Address Decal"	,
mca	:	"Caution marking"	,
mcc	:	"Country code"	,
mce	:	"ACEP marking"	,
mch	:	"Height caution marking"	,
mco	:	"Container - entire"	,
mcs	:	"Class survey marking"	,
mcu	:	"Customers markings"	,
mcw	:	"Width caution marking"	,
mfs	:	"Marking - full set"	,
mhc	:	"High cube stripe"	,
mht	:	"Height marking"	,
min	:	"Collapsible flatrack instruction decal"	,
mis	:	"Identification marking set"	,
mmi	:	"Mass marking"	,
moc	:	"Owner's code"	,
mol	:	"Owner's logo"	,
mpc	:	"Customs plate"	,
mpd	:	"Consolidated data plate"	,
mpl	:	"Cargo label plate"	,
mpm	:	"Manufacturer's plate"	,
mpo	:	"Owner's plate"	,
mps	:	"CSC plates"	,
mpt	:	"Tank plate"	,
mru	:	"Other markings"	,
msd	:	"Marking - single digit or character"	,
msn	:	"Serial number and check digit"	,
mst	:	"Size type marking"	,
mtt	:	"Timber chemical treatment"	,
mui	:	"UIC decal"	,
paa	:	"Panel assembly"	,
pbh	:	"Panel - behind hinge"	,
pbk	:	"Bulkhead"	,
pfx	:	"Panel - fixing strip"	,
pip	:	"Panel - inner face"	,
pla	:	"Post locking bolt assembly"	,
plb	:	"Post locking bolt"	,
pll	:	"Post locking bolt latch"	,
pln	:	"Post locking bolt latch screw"	,
plr	:	"Post locking bolt bracket"	,
pls	:	"Post locking screw"	,
pop	:	"Panel - outer face"	,
ppm	:	"Panel - plymetal"	,
pps	:	"Pivot Safety Pin Retainer"	,
ppw	:	"Panel - plywood lining"	,
prv	:	"Panel Assembly - Rivet / Fixing"	,
psc	:	"Panel - steel corrugation"	,
psf	:	"Panel - steel flat"	,
raa	:	"Roof - complete assembly"	,
rbh	:	"Roof bow holder"	,
rbo	:	"Roof bow"	,
rbp	:	"Roof bow pin"	,
rbs	:	"Roof bow securing device"	,
rcg	:	"Roof Corner Gusset"	,
rci	:	"Rail cone protector recess"	,
rck	:	"Cam keeper"	,
rdp	:	"Rail doubling plate"	,
rhl	:	"Rear header latch"	,
riw	:	"Rail inner web"	,
rla	:	"Rails assembly"	,
rle	:	"Rail - exterior component"	,
rlf	:	"Rail lower flange"	,
rlg	:	"Rail gusset"	,
rli	:	"Rail - interior component"	,
rll	:	"Rear header - hinge lug"	,
rlt	:	"Rail whole section"	,
rlw	:	"Rail web"	,
rng	:	"Rain Gutter"	,
rpp	:	"Piggybacker Rail"	,
rrt	:	"Header - swing or removable"	,
rtl	:	"Gooseneck tunnel rail"	,
ruf	:	"Rail upper flange"	,
rup	:	"Rail doubler plate"	,
rwb	:	"Water box"	,
saa	:	"Sidewall - complete assembly"	,
sbr	:	"Side bar"	,
sbs	:	"Side bar socket"	,
sca	:	"Twistlock Assembly"	,
scb	:	"Stacking cone - fliplock pivotbar"	,
scc	:	"Stacking cone and chain - fixed and removable"	,
sch	:	"Stanchion chain hook"	,
scs	:	"Split corner casting"	,
sea	:	"Sealer (for joining components)"	,
sfr	:	"Steel Floor Recess"	,
sga	:	"Side gate assembly"	,
sgf	:	"Side gate frame"	,
sgm	:	"Side gate mesh"	,
sgp	:	"Side gate pin"	,
sho	:	"Dumbell Hammer/Sliding Hammer Only"	,
skp	:	"Replace Stanchion Pocket/Stake Pocket"	,
slc	:	"Stanchion lashing chain"	,
slg	:	"Stacking legs	"	,
sll	:	"Replace Stanchion lashing loop/Lashing ring"	,
sls	:	"Stanchion lashing system"	,
spi	:	"Side post - inner"	,
spo	:	"Side post - outer"	,
sst	:	"Stanchion socket"	,
stc	:	"Stanchion"	,
stp	:	"Stanchion pocket"	,
tic	:	"TIR cord"	,
tir	:	"TIR cord ring"	,
tmc	:	"Twistlock Mounting Connection"	,
tna	:	"Tarpaulin assembly"	,
tnb	:	"Tarpaulin belt"	,
tnc	:	"Tarpaulin rubber cord"	,
tng	:	"Tarpaulin grommet"	,
tns	:	"Tarpaulin customs seal point"	,
tnx	:	"Tarpaulin fixing strip"	,
tph	:	"Tarpaulin pinhole"	,
tua	:	"Tunnel assembly"	,
tub	:	"Tunnel bolster"	,
tuc	:	"Tunnel cross-member"	,
tup	:	"Tunnel plate"	,
twh	:	"Twistlock Storage Pocket"	,
uaa	:	"Understructure - complete assembly"	,
ujt	:	"Joint between components"	,
vjt	:	"Joint between components"	,
vra	:	"Ventilator assembly"	,
vrb	:	"Ventilator baffle"	,
vrg	:	"Ventilator grid"	,
vrr	:	"Ventilator cover"	,
zzz	:	"Miscellaneous"	,

        };

        const damage = {
            bk	:	"Blocked"	,
bn	:	"Burned"	,
br	:	"Broken / Split"	,
bt	:	"Bent"	,
bu	:	"Bulged"	,
bw	:	"Bowed"	,
cd	:	"Consequential damage"	,
ch	:	"Corroded and holed"	,
ck	:	"Cracked"	,
cl	:	"Compression line"	,
co	:	"Corroded / Rusty"	,
ct	:	"Contaminated"	,
cu	:	"Cut"	,
cw	:	"Cracked weld"	,
db	:	"Debris / Dunnage"	,
dh	:	"Dented and holed"	,
dl	:	"Delaminated"	,
dt	:	"Dent"	,
dy	:	"Dirty"	,
ef	:	"Equipment Failure"	,
fd	:	"Forklift damage"	,
fl	:	"Floor refurbishment program"	,
fq	:	"Food quality"	,
fz	:	"Frozen"	,
gd	:	"Gouged"	,
go	:	"GRP surface crack"	,
gp	:	"GRP surface and plywood crack"	,
ho	:	"Holed"	,
ic	:	"Improper cleaning"	,
in	:	"New improper repair"	,
io	:	"Old improper repair"	,
ip	:	"Imploded"	,
ir	:	"Improper repair"	,
lk	:	"Leak"	,
lo	:	"Loose"	,
ma	:	"Misaligned"	,
me	:	"Manufacturer defect"	,
ml	:	"Markings / Labels"	,
mm	:	"Mismatched"	,
mn	:	"New manufacturing defect"	,
ms	:	"Missing / Lost"	,
ni	:	"Not within ISO dimensions"	,
nl	:	"Nails"	,
no	:	"Not as required by owner"	,
np	:	"Not in place"	,
nt	:	"Not to TIR requirements"	,
nv	:	"Not as required by user"	,
od	:	"Out-of-date"	,
oe	:	"Operator failure"	,
ol	:	"Oil saturated"	,
oo	:	"Overhead obstruction"	,
or	:	"Odour"	,
os	:	"Oil stains"	,
ou	:	"Other unacceptable repairs"	,
pd	:	"Pushed down"	,
pf	:	"Paint failure"	,
ph	:	"Pin holes"	,
pi	:	"Pushed in"	,
pm	:	"Preventive maintenance"	,
po	:	"Pushed out"	,
ps	:	"Pitted surface"	,
pu	:	"Pushed up"	,
ra	:	"Remove for access"	,
rc	:	"Conversion required"	,
rd	:	"Rollover damage"	,
rn	:	"Repair necessary"	,
ro	:	"Rotted"	,
rp	:	"Refurbishment program"	,
rt	:	"Rotten"	,
rv	:	"Refurbishment Program"	,
sa	:	"Scratched / Abraded moving part"	,
sd	:	"Stretched"	,
sr	:	"Shrunk"	,
st	:	"Saturated/wet"	,
tr	:	"Test required"	,
wa	:	"Warped"	,
wh	:	"Wet hides"	,
wm	:	"Wrong material"	,
wn	:	"Worn"	,
wt	:	"Wear and tear"	,
zz	:	"Not applicable"	,

        };

        const repair = {
            ab	:	"Abrasive clean and paint"	,
ac	:	"Air clean"	,
ad	:	"Add"	,
aj	:	"Adjust"	,
bu	:	"Blank out"	,
bx	:	"Fit by MNR stock"	,
cc	:	"Chemical clean"	,
cn	:	"Conversion"	,
co	:	"Convert"	,
dc	:	"Dismantle and clean"	,
dh	:	"Dispatch fee"	,
do	:	"Deodorize"	,
dr	:	"Drain"	,
du	:	"Dry out"	,
ec	:	"Emergency service call"	,
ex	:	"Fit part ex owners stock"	,
fl	:	"Floor refurbishment"	,
fr	:	"Free"	,
ft	:	"Refit"	,
gs	:	"Straighten"	,
gt	:	"Remove glue and tape"	,
gw	:	"Straighten and weld"	,
hn	:	"Handling"	,
in	:	"Install"	,
ip	:	"Inspect and report"	,
it	:	"Insert"	,
lc	:	"Lubricate"	,
mc	:	"Mechanical Cleaning (scrape off paint)"	,
md	:	"Modifications, miscellaneous"	,
mf	:	"Mileage fee"	,
mk	:	"Re-mark"	,
mv	:	"Remove markings"	,
na	:	"No action necessary"	,
op	:	"Overlapping partial section"	,
ox	:	"Overlay"	,
pa	:	"Apply paint"	,
pc	:	"Polish clean"	,
pp	:	"Pickle/Passivate"	,
pr	:	"Partial refurbishment"	,
ps	:	"Surface preparation and paint"	,
pt	:	"Patch"	,
pv	:	"Repairs prior to refurbishment"	,
pw	:	"Prepare for work"	,
ra	:	"Re-align"	,
rb	:	"Rebuild"	,
rc	:	"Recondition / Refurbish"	,
rd	:	"Remove and dispose"	,
re	:	"Resecure"	,
rg	:	"Re-glass"	,
ri	:	"Reinforce"	,
rm	:	"Remove (without replacement)"	,
rp	:	"Replace"	,
rr	:	"Remove and refit"	,
rs	:	"Straighten and resecure"	,
rt	:	"Re-rate"	,
ru	:	"Re-bush"	,
rx	:	"Recondition/refurbish"	,
sc	:	"Steam clean"	,
sd	:	"Sand"	,
se	:	"Seal / Reseal"	,
si	:	"Splice"	,
sn	:	"Section"	,
sp	:	"Special repair necessary"	,
sr	:	"Reseal"	,
tb	:	"Temporary repair"	,
tf	:	"Toll fee"	,
tp	:	"Take photos"	,
tr	:	"Temporary repair"	,
vm	:	"Preventive maintenance"	,
wd	:	"Weld"	,
wp	:	"Sweep"	,
ww	:	"Water wash"	,
xw	:	"Grind and weld"	,
zz	:	"Not applicable"	,

        };

   const codeMapping = { ...components, ...damage, ...repair };

    function toLowerCase(inputString) {
        return inputString.toLowerCase();
    }

function getConcatenatedMeaning(codes) {
    return codes.map(code => codeMapping[code] || 'unknown').join(' ');
}

function validateForm() {
    const componentsInput = toLowerCase(document.getElementById('components').value.trim());
    const damageInput = toLowerCase(document.getElementById('damage').value.trim());
    const repairInput = toLowerCase(document.getElementById('repair').value.trim());
    
    const codes = [componentsInput, damageInput, repairInput];
    const summary = getConcatenatedMeaning(codes);
    
    document.getElementById('summary').value = summary.trim();
    
    return false; // Prevent form submission
}
